version: '3.1'
services:
  odoo:
    image: odoo:16.0
    env_file: myenvfile.env
    depends_on:
      - psql
    ports:
      - "8069:8069" #port mapping(custom-port:8069)
    volumes:
      - ./data/odoo:/var/lib/odoo
      - ./config:/etc/odoo
      - ./custom-addons:/mnt/extra-addons
      - ./logs:/var/log/odoo
  psql:
    image: postgres:13
    env_file: myenvfile.env
    ports:
      - "54321:5432"
    volumes:
      - ./data/odoo:/var/lib/pgsql/data/pgdata