version: "3.7"
services:
  odoo:
    image: odoo:16.0
    depends_on:
      - psql
    ports:
      - "8069:8069"
      - "8072:8072"
    volumes:
      - ./data/odoo:/var/lib/odoo
      - ./config:/etc/odoo
      - ./custom-addons:/mnt/extra-addons
      - ./logs:/var/log/odoo
    networks:
      - odoo16-network
  psql:
    image: postgres:13
    environment:
      POSTGRES_DB: postgres 
      POSTGRES_PASSWORD: odoo16 
      POSTGRES_USER: odoo16 
      PGDATA: /var/lib/pgsql/data/pgdata 
    volumes:
      - ./data/pgsql:/var/lib/pgsql/data/pgdata
    networks:
      - odoo16-network
networks:
  odoo16-network:
    driver: bridge